version: '3.8'

services:
  ambiente1:
    build:
      context: ./ambiente1
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./ambiente1:/usr/src/app
    networks:
      - ambiente1-network

networks:
  ambiente1-network:
    driver: bridge

